version: "3.9"

services:
  db:
      image: postgres:15
      container_name: userdb
      environment:
        POSTGRES_DB: users
        POSTGRES_USER: ${DB_USERNAME:?DB_USERNAME is required}
        POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:?RABBITMQ_USERNAME is required}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?RABBITMQ_PASSWORD is required}
    ports:
      - "5672:5672"    # AMQP communication
      - "15672:15672"  # Web UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
volumes:
  pgdata:
  rabbitmq-data:
  rabbitmq-logs: